# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-10 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181210_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mdp',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
