# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-10 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181210_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_prestation',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
