# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-10 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181210_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='niv_autorisation',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Niv_autorisation'),
        ),
    ]
