# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-10 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181210_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Type_prestation'),
        ),
    ]
